version: "3.7"
services:
  # INFRASTRUCTURE - DATABASE
  kl-mysql:
    container_name: kl-mysql
    image: mysql:5.7
    restart: always
    networks:
      - dial
    environment:
      - MYSQL_ROOT_PASSWORD=masterkey
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "3306:3306"
    volumes:
      - $HOME/data/kl-mysql:/var/lib/mysql

  # INFRASTRUCTURE - REDIS
  kl-redis:
    container_name: kl-redis
    image: redis:latest
    restart: always
    networks:
      - kl
    ports:
      - "6379:6379"
    volumes:
      - $HOME/data/kl-redis:/data

  # INFRASTRUCTURE - REDIS CLIENT
  kl-redis-commander:
    container_name: kl-redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    networks:
      - kl
    environment:
      - REDIS_HOSTS=kl-redis
    ports:
      - "8081:8081"

networks:
  kl:
    external: true
