export const CHANGE_CALL_ANALYSIS_DATA = "CHANGE_CALL_ANALYSIS_DATA";
export const SELECT_CALL_ANALYSIS_ITEM = "SELECT_CALL_ANALYSIS_ITEM";
export const SET_SCALE_TO_GEO_MAP = "SET_SCALE_TO_GEO_MAP";
// export const DESELECT_CALL_ANALYSIS_ITEM = "DESELECT_CALL_ANALYSIS_ITEM";
