name: DialStatisticApi - PROD
on:
  workflow_dispatch:

env:
  KUBECTL_FILTER: "app=kl-statistic"
  IMAGE_TAG: production
  IMAGE: gcr.io/kl-manage/kl-statistic

jobs:
  dirty_hack:
    steps:
      - run: |
          echo ""
    runs-on: arc-runner-set
    outputs:
      IMAGE: ${{env.IMAGE}}
      KUBE_FILTER: ${{env.KUBECTL_FILTER}}
      client: "CNV_PROD"

  deploy_app:
    needs: dirty_hack
    name: build & deploy app with share wf
    permissions:
      contents: "read"
      id-token: "write"

    uses: Plat4Me/shared_workflows/.github/workflows/deploy_on_prod_bm.yaml@main
    with:
      KUBECTL_FILTER: ${{ needs.dirty_hack.outputs.KUBE_FILTER }}
      image_name: ${{needs.dirty_hack.outputs.IMAGE}}
      client: ${{needs.dirty_hack.outputs.client}}
    secrets: inherit
#  build:
#    name: Setup, Build, Deploy
#    runs-on: self-hosted
#    environment: production
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: GCP auth
#        id: auth
#        uses: google-github-actions/auth@v0
#        with:
#          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
#
#      - uses: 'docker/login-action@v1'
#        with:
#          registry: 'gcr.io' # or REGION-docker.pkg.dev
#          username: _json_key
#          password: "${{ secrets.GCP_CREDENTIALS }}"
#
#      - uses: 'docker/login-action@v1'
#        with:
#          registry: 'europe-west1-docker.pkg.dev' # or REGION-docker.pkg.dev
#          username: _json_key
#          password: "${{ secrets.GCP_CREDENTIALS }}"
#
#      - name: Set up GKE credentials
#        run: |-
#          mkdir -p ~/.kube
#          echo "${{secrets.K8S_CNV_PROD}}" > ~/.kube/config
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Pull, Retag and Publish
#        run: |-
#          docker pull $IMAGE:qa
#          docker tag  $IMAGE:qa $IMAGE:$IMAGE_TAG
#          docker push $IMAGE:$IMAGE_TAG
#
#      # Deploy the Docker image to the GKE cluster
#      - name: Deploy
#        run: |-
#          kubectl get deployments -l ${{ env.KUBECTL_FILTER }} -o name --no-headers | xargs -I{} sh -c 'kubectl rollout restart {}'
