name: Referral Program Tracker - Training

on:
  workflow_dispatch:

env:
  ENVIRONMENT: production
  TAG: training
  SERVICE_TYPE: deployment
  SERVICE_NAME: kl-manager-web
  IMAGE: gcr.io/kl-manage/kl-manager-web
  TARGET_DOCKERFILE: Dockerfile


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: self-hosted
    environment: production
    
    permissions:
      contents: "read"
      id-token: "write"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Alternative option - authentication via credentials json
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - uses: "docker/login-action@v2"
        with:
          registry: "gcr.io" # or REGION-docker.pkg.dev
          username: _json_key
          password: "${{ secrets.GCP_CREDENTIALS }}"
      
      # Get the GKE credentials, so we can deploy to the cluster
      - name: Set up GKE credentials
        run: |-
          mkdir -p ~/.kube
          echo "${{secrets.K8S_TP_STAGING}}" > ~/.kube/config 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push App
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.TARGET_DOCKERFILE }}
          push: true
          tags: |
            ${{ env.IMAGE }}:${{github.sha}}
            ${{ env.IMAGE }}:${{env.TAG}}
          build-args: |
            BRANCH_NAME="${{github.ref_name}}"
            GITHUB_TOKEN="${{ secrets.NPM_TOKEN }}"

      - name: Deploy
        run: |-
          kubectl rollout restart $SERVICE_TYPE/$SERVICE_NAME